# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'riders_app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for riders_app
  pod 'SideMenu', '~> 4.0'
  pod 'SlideMenuControllerSwift', '~> 4.0'
  pod 'SideMenuSwift', '~> 0.5'
  pod 'Alamofire', '~> 4.7'
end
